name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Login to Vercel
        run: vercel login --email nonthakon.t3@gmail.com --token A66FFa2PJairIfVUSHPJyezj # Use token for better security
        
      - name: Deploy to Vercel
        run: vercel --prod
